### ISSUE TITLE
Góp ý - Báo lỗi

### ISSUE THREAD

**Issue by Hungs20** [Hungs20/Themis#1]
Mọi người góp ý , báo lỗi ở đây giúp mình nhé.

**Comment by Hungs20** [comment]
![screenshot 22](https://user-images.githubusercontent.com/20833690/43200380-9f9b0b50-903f-11e8-9add-228cd201805b.png)
![screenshot 23](https://user-images.githubusercontent.com/20833690/43200381-9fd015de-903f-11e8-8176-08713181a5e7.png)
![screenshot 24](https://user-images.githubusercontent.com/20833690/43200382-a0056874-903f-11e8-9bc5-0deb65cec071.png)
![screenshot 25](https://user-images.githubusercontent.com/20833690/43200384-a03bdc4c-903f-11e8-83d1-a8c58eabf0d0.png)
![screenshot 26](https://user-images.githubusercontent.com/20833690/43200385-a0718ef0-903f-11e8-89df-aac8d0c05414.png)
![screenshot 27](https://user-images.githubusercontent.com/20833690/43200386-a0a96ea6-903f-11e8-9bad-07dac7ebf87f.png)
![screenshot 28](https://user-images.githubusercontent.com/20833690/43200388-a0e12e54-903f-11e8-9fe0-7a01032255dd.png)
![screenshot 29](https://user-images.githubusercontent.com/20833690/43200389-a11a1778-903f-11e8-9631-417551dc39f6.png)
![screenshot 30](https://user-images.githubusercontent.com/20833690/43200390-a14cd14a-903f-11e8-9f17-401c6d281cf4.png)
![screenshot 31](https://user-images.githubusercontent.com/20833690/43200391-a17d2a48-903f-11e8-9971-3d33a0489402.png)
![screenshot 32](https://user-images.githubusercontent.com/20833690/43200392-a1b3434e-903f-11e8-97b2-d2343f8b50cd.png)
![screenshot 33](https://user-images.githubusercontent.com/20833690/43200393-a1e97fa4-903f-11e8-9547-c9ce54fb5a0c.png)
![screenshot 34](https://user-images.githubusercontent.com/20833690/43200395-a2230fd0-903f-11e8-80de-517dbcfe27df.png)
![screenshot 35](https://user-images.githubusercontent.com/20833690/43200396-a28f8160-903f-11e8-8729-a9b4441d876f.png)

**Comment by yinlin49** [comment]
Bạn xài trình đọc gì vậy ? Có phải là xampp ?

**Comment by Hungs20** [comment]
Mình dùng uniform server . Php bản 5.4

**Comment by annast9908** [comment]
Mình bị lỗi ranking. Bạn giúp mình được không?
![image](https://user-images.githubusercontent.com/46856122/51434717-f6574800-1c99-11e9-8f10-4ba47af57faa.png)

**Comment by Hungs20** [comment]
> Mình bị lỗi ranking. Bạn giúp mình được không?
> ![image](https://user-images.githubusercontent.com/46856122/51434717-f6574800-1c99-11e9-8f10-4ba47af57faa.png)

Lỗi như nào vậy bạn

**Comment by annast9908** [comment]
> > Mình bị lỗi ranking. Bạn giúp mình được không?
> > ![image](https://user-images.githubusercontent.com/46856122/51434717-f6574800-1c99-11e9-8f10-4ba47af57faa.png)
> 
> Lỗi như nào vậy bạn

Mình nộp bài xong thì tên tài khoản hiện trên dòng chứa tên bài, và điểm cũng bị lỗi

**Comment by Hungs20** [comment]
> > > Mình bị lỗi ranking. Bạn giúp mình được không?
> > > ![image](https://user-images.githubusercontent.com/46856122/51434717-f6574800-1c99-11e9-8f10-4ba47af57faa.png)
> > 
> > 
> > Lỗi như nào vậy bạn
> 
> Mình nộp bài xong thì tên tài khoản hiện trên dòng chứa tên bài, và điểm cũng bị lỗi

Bạn thử cài lại code xem có bị lỗi như vậy không . Phiên bản php là 5.4

**Comment by annast9908** [comment]
Bạn cho mình link tải được không? mình sợ tải sai.

**Comment by Hungs20** [comment]
> Bạn cho mình link tải được không? mình sợ tải sai.

Code trên là bản mới nhất đó bạn

**Comment by kidzukii** [comment]
Bạn ơi trong Themis chọn thư mục thí sinh nào ạ?

**Comment by duongnotnhan** [comment]
Làm sao để mình có thể thêm một ngôn ngữ khác cho IDE vậy bạn?
Mình đang tính thêm Python (.py) vào mà chưa biết nên làm gì.

**Comment by duongnotnhan** [comment]
Mình có cách nào để thay đổi khoảng cách Tab trong IDE .py từ 2 spaces thành 4 spaces không vậy bạn?

**Comment by VoTaGiaHuy** [comment]
Bạn có thể hướng dẫn mình cách dùng được không?

**Comment by VoTaGiaHuy** [comment]
Cho mình hỏi là tại sao ide của mình không hiển thị vậy?

![screenshot_1699882934](https://github.com/Hungs20/Themis/assets/117757298/c178d84d-bfe0-44df-add5-aa891b82a7b1)

**Comment by duongnotnhan** [comment]
Thay đổi hệ thống tính điểm:
- Lưu lại kết quả chấm của tất cả các lần nộp
- Mỗi bài tập được tính điểm bằng điểm của bài nộp có điểm cao nhất
- Phần bảng xếp hạng bổ sung thêm thời gian tổng (tham khảo hệ thống VNOJ)
