### ISSUE TITLE
Fix giùm mình bug này nha 

### ISSUE THREAD

**Issue by Toxica20002** [Hungs20/Themis#2]
![image](https://user-images.githubusercontent.com/42279296/43972590-10a444f8-9cff-11e8-8b8b-91bab2d1b89d.png)
![image](https://user-images.githubusercontent.com/42279296/43972686-61fd7d9c-9cff-11e8-9f6e-24e2473d010c.png)
![image](https://user-images.githubusercontent.com/42279296/43972698-68e48952-9cff-11e8-8ec3-0c330cd53d09.png)

**Comment by Hungs20** [comment]
Bạn thử dùng phiên bản php 5.4 xem còn bị lỗi không.

**Comment by yinlin49** [comment]
Mình sử dụng thử rồi cảm ơn bạn rất nhiều và trang web của bạn. Mong bạn có
thể phát triển hơn để trang web được sử dụng rộng rãi không chỉ riêng mình
🙂

Vào 00:46, CN, 12 Th8, 2018 Chu Văn Hưng <notifications@github.com> đã viết:

**Comment by Hungs20** [comment]
Cám ơn bạn đã quan tâm. Nếu có bất kì bug  hay ý tưởng nào mong bạn phản hồi lại để trang web được hoàn thiện tốt nhất.
